### ISSUE TITLE
[question] Would you like to work on something together?

### ISSUE THREAD

**Issue by Isaiah08-D** [SiddhantManze/My-Codechef-submission#1]
I see on your profile that you would like to make a project with someone else. I enjoy backend programming, so we could collaborate on website if you want. I had to post this here because I can't create an issue on your main repository :)

**Comment by SiddhantManze** [comment]
yee sure... why not

**Comment by Isaiah08-D** [comment]
ok! sorry for not seeing this earlier what do you think would be fun

**Comment by Isaiah08-D** [comment]
oops i didnt mean to close it

**Comment by SiddhantManze** [comment]
creating a startup website

**Comment by SiddhantManze** [comment]
I'm new to GitHub I'm not yet familiar  with Github

**Comment by SiddhantManze** [comment]
hello, want to participate with me in a hackathon on devpost 
https://devpost.com/siddhantmanze?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav

**Comment by Isaiah08-D** [comment]
Sure! Maybe https://hackthisfall.devpost.com?

**Comment by SiddhantManze** [comment]
are u frontend or backend dev
i already have a team of 3 dev

**Comment by Isaiah08-D** [comment]
mainly backend

**Comment by SiddhantManze** [comment]
join this link
https://chat.whatsapp.com/HDW91EY7S6G8bO3vDK6HhC
we have created a group for hackathon

**Comment by Isaiah08-D** [comment]
I don't have a phone sorry. I can do discord though.

**Comment by SiddhantManze** [comment]
Al right np
